FROM node:18-alpine

WORKDIR /app

# Copia package.json e package-lock
COPY package*.json ./

RUN npm install

# Copia o restante do código
COPY . .

# Habilita o hot reload
ENV WATCHPACK_POLLING=true

EXPOSE 3005

CMD ["npm", "run", "dev"]
